CREATE TABLE IF NOT EXISTS users
(
    id integer PRIMARY KEY,
    user_name character varying COLLATE pg_catalog."default" NOT NULL,
    user_password character varying COLLATE pg_catalog."default" NOT NULL,
    status integer DEFAULT 0,
    create_time timestamp without time zone DEFAULT (now())::timestamp(0) without time zone,
    modify_time timestamp without time zone DEFAULT (now())::timestamp(0) without time zone,
    phone character varying COLLATE pg_catalog."default" NOT NULL
)

TABLESPACE pg_default;

ALTER TABLE users
    OWNER to postgres;

ALTER TABLE users
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 );

COMMENT ON TABLE users
    IS '用户表';

COMMENT ON COLUMN users.user_name
    IS '用户账号';

COMMENT ON COLUMN users.user_password
    IS '用户密码';

COMMENT ON COLUMN users.status
    IS '用户登录状态 0:未登录 1：已登录';

COMMENT ON COLUMN users.create_time
    IS '创建日期';

COMMENT ON COLUMN users.modify_time
    IS '修改时间';

COMMENT ON COLUMN users.id
    IS '自增主键';

COMMENT ON COLUMN users.phone
    IS 'phone number ';
-- Index: uni_phone_idx

-- DROP INDEX uni_phone_idx;

CREATE UNIQUE INDEX uni_phone_idx
    ON users USING btree
    (phone COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;
